function expr = Lotka0x2DVolterra(t,in2,in3)
%LOTKA0X2DVOLTERRA
%    EXPR = LOTKA0X2DVOLTERRA(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Oct-2021 19:01:56

D = in2(2,:);
P = in2(1,:);
param5 = in3(:,1);
param6 = in3(:,2);
param7 = in3(:,3);
param8 = in3(:,4);
expr = [P.*param5-D.*P.*param6;-D.*param8+D.*P.*param7];
