function expr = Lotka0x2DVolterra(t,in2,in3)
%LOTKA0X2DVOLTERRA
%    EXPR = LOTKA0X2DVOLTERRA(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Nov-2021 15:51:25

D = in2(2,:);
P = in2(1,:);
param13 = in3(:,1);
param14 = in3(:,2);
param15 = in3(:,3);
param16 = in3(:,4);
expr = [P.*param13-D.*P.*param14;-D.*param16+D.*P.*param15];
