function expr = Lotka0x2DVolterra(t,in2,in3)
%LOTKA0X2DVOLTERRA
%    EXPR = LOTKA0X2DVOLTERRA(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-May-2021 13:15:14

D = in2(2,:);
P = in2(1,:);
param165 = in3(:,1);
param166 = in3(:,2);
param167 = in3(:,3);
param168 = in3(:,4);
expr = [P.*param165-D.*P.*param166;-D.*param168+D.*P.*param167];
